### ISSUE TITLE
HP DL385 G7 fix!

### ISSUE THREAD

**Issue by emanuelebruno** [rickh1965/base_docker_roles#2]
Hi,
the onboard P410i is unrecognized by your script if the server is a HP DL385 G7... To fix it I changed from :

      shell:  "/root/hpsahba/hpsahba -i /dev/sg0"

to

      shell:  "/root/hpsahba/hpsahba -i /dev/sg1"

**Comment by rickh1965** [comment]
I'll add documentation on the device name which may in some cases be different fron /dev/sg0
